### ISSUE TITLE
Bootstrap tabs bug...

### ISSUE THREAD

**Issue by Faks** [FlorianKoerner/equalHeight.js#4]
if try use data-eqh it just wont work inside other tab .... funny tried jquery.noconflict but it didn't helped...

**Comment by FlorianKoerner** [comment]
Thank you for trying out `equalHeight.js`. The plugin only works on visible items. If an item gets visible, you have to tell `equalHeight.js` to recalculate the element dimensions.

This example should work in BS3:

```
var eqh = $('[data-eqh]').equalHeight();

$('a[data-toggle="tab"]').on('shown.bs.tab', function () {
  equalHeight.recalculate();
});
```

If you have any further questions, let me know.

**Comment by Faks** [comment]
Thanks for the response and help took a little dive in your found little mistake in typo but thing serious works like charm thanks for help the help i hope for other it will also help :+1:
